name: CI

on: [push, pull_request]

jobs:
  build-posix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]
        build_type: [tiny, regular]
        lua_engine: [LuaJIT, Lua]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure
      run: make ${{ matrix.build_type }} WITH_LUA_ENGINE=${{ matrix.lua_engine }}

    - name: Build
      run: make

    - name: Test
      run: make test

  build-mingw:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [tiny, regular]
        lua_engine: [LuaJIT, Lua]
        msystem: [mingw32, mingw64]

    steps:
    - name: 'Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        pacboy: toolchain:p cmake:p nasm:p
        install: make

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure
      run: mingw32-make ${{ matrix.build_type }} WITH_LUA_ENGINE=${{ matrix.lua_engine }} GENERATOR="MinGW Makefiles"

    - name: Build
      run: mingw32-make

    - name: Test
      run: mingw32-make test

  build-msvc:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [tiny, regular]
        lua_engine: [LuaJIT, Lua]
        arch: [x64, x86]

    steps:
    - name: Step MSVC Developer Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Install NASM
      run: |
        choco install nasm
        echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure
      run: nmake ${{ matrix.build_type }} WITH_LUA_ENGINE=${{ matrix.lua_engine }}

    - name: Build
      run: nmake

    - name: Test
      run: nmake test
