name: MacOS

on: [push, pull_request, workflow_dispatch]

jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        type: [tiny, regular, regular-asm]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Find Version
        run: |
          git fetch --tags --prune --progress --no-recurse-submodules --depth=1 origin master

          latest_tagged=$(git rev-list --tags --max-count=1)
          version=$(git describe --tags "$latest_tagged")
          if [ "${latest_tagged}" != "$(git rev-parse HEAD)" ]; then
            version="${version}-dev"
          fi

          echo $version > VERSION

      - name: Setup CCache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}-x86_64-${{ matrix.type }}-${{ github.sha }}

      - name: Install Dependencies
        run: |
          echo "/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH" > $GITHUB_PATH

      - name: Configure
        run: make ${{ matrix.type }}

      - name: Build
        run: make

      - name: Test
        run: make test

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: luvi-${{ matrix.type }}-Darwin-x86_64
          path: build/luvi
